pipeline {
    agent any
    environment {
        IMAGE_NAME = 'gurkirpa'  
        DOCKERFILE_PATH = './Dockerfile'
    }
    stages {
        stage('Checkout'){
           steps {
                git credentialsId: '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', 
                url: 'https://github.com/Gurkirpa/jenkins.git',
                branch: 'main'
           }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker Image..."
                    sh "docker build -t ${IMAGE_NAME} -f ${DOCKERFILE_PATH} ."
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    echo "Running Docker Container..."
                    sh "docker run --rm ${IMAGE_NAME}"
                }
            }
        }
    }
}

