pipeline {
    agent any
    environment {
        IMAGE_NAME = 'gurkirpa'  // Name of the Docker image to create
    }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    echo "Building Docker Image..."
                    sh "docker build -t ${IMAGE_NAME} -f /https://github.com/Gurkirpa/jenkins.git/chatgpt/Dockerfile ."
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    echo "Running Docker Container..."
                    sh "docker run --rm ${IMAGE_NAME}"
                }
            }
        }
    }
}

