pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--user root -v /var/run/docker.sock:/var/run/docker.sock' 
    }
  }
  stages {
    stage('Checkout') {
      steps {
        sh 'echo passed'
        git branch: 'main', https://github.com/Gurkirpa/jenkins.git'
      }
    }
	stage('Test') {
      steps {
        sh 'cd Dockerhub'
      }
    }
	stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "gurkirpa/ultimate-cicd:${BUILD_NUMBER}"
        // DOCKERFILE_LOCATION = "Dockerhub/Dockerfile"
        REGISTRY_CREDENTIALS = credentials('dockerhub-creds')
      }
      steps {
        script {
            sh 'cd Dockerhub && docker build -t ${DOCKER_IMAGE} .'
        }
      }
    }
  }
}
