pipeline {
    agent {
        docker { image 'docker:latest' }
    }
    environment {
        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'  
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh ''' 
		      echo "Build Docker Image"
		      docker build -t gurkirpa/cicd-docker:${BUILD_NUMBER} .
                      '''
		}
				
            }
        }
        
        stage('Run Docker Container') {
            steps {
                script {
                    sh '''
		      echo "Run Container"
		      docker run -d --name test_container gurkirpa/cicd-docker:${BUILD_NUMBER}
                      '''
                }
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                script {
                    // Login to Docker Hub
                    withCredentials([usernamePassword(credentialsId: "${DOCKERHUB_CREDENTIALS}", passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                        sh 'echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin'
                    }
                    
                    // Push the image
                    sh 'docker push $gurkirpa/cicd-docker:${BUILD_NUMBER}'
                    
                    // Logout from Docker Hub
                    sh 'docker logout'
                }
            }
        }
    }
    post {
        always {
            // Cleanup the test container if it's still running
            script {
                sh 'docker rm -f test_container || true'
            }
        }
        cleanup {
            // Cleanup Docker images and containers to save space
            sh 'docker rmi gurkirpa/cicd-docker:${BUILD_NUMBER} || true'
        }
    }
}
