pipeline {
    
    agent any 
    
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'github-cred', 
                url: 'https://github.com/Gurkirpa/jenkins.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t gurkirpa/cicd-docker:${BUILD_NUMBER} .
                    '''
                }
            }
        }
    }
}	
